version: '3.8'

services:
  payment-api:
    build: .
    container_name: payment-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL_FILE=/run/secrets/db_url
      - STRIPE_SECRET_KEY_FILE=/run/secrets/stripe_secret
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - WEBHOOK_SECRET_FILE=/run/secrets/webhook_secret
    secrets:
      - db_url
      - stripe_secret
      - jwt_secret
      - webhook_secret
    ports:
      - "3000:3000"
    networks:
      - payment-network
    volumes:
      - logs:/app/logs:rw
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  redis:
    image: redis:7-alpine
    container_name: payment-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - payment-network
    volumes:
      - redis-data:/data:rw
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: payment-nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - logs:/var/log/nginx:rw
    networks:
      - payment-network
    depends_on:
      - payment-api

  prometheus:
    image: prom/prometheus:latest
    container_name: payment-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus:rw
    networks:
      - payment-network

  grafana:
    image: grafana/grafana:latest
    container_name: payment-grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD_FILE=/run/secrets/grafana_password
    secrets:
      - grafana_password
    volumes:
      - grafana-data:/var/lib/grafana:rw
      - ./monitoring/grafana:/etc/grafana/provisioning:ro
    networks:
      - payment-network

secrets:
  db_url:
    external: true
  stripe_secret:
    external: true
  jwt_secret:
    external: true
  webhook_secret:
    external: true
  grafana_password:
    external: true

volumes:
  redis-data:
    driver: local
  logs:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  payment-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16